// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeeC-BvOGV3d8GEJPou6fLWRo_PbgHP0c',
    appId: '1:785051614310:web:2ba45805511bb446f481a7',
    messagingSenderId: '785051614310',
    projectId: 'sanhuu-app',
    authDomain: 'sanhuu-app.firebaseapp.com',
    storageBucket: 'sanhuu-app.firebasestorage.app',
    measurementId: 'G-K786Q4DCXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwSn69bXaQh0r5Sz8GCfn7Zh6dXXxed5o',
    appId: '1:785051614310:android:e7580583bdcda4cdf481a7',
    messagingSenderId: '785051614310',
    projectId: 'sanhuu-app',
    storageBucket: 'sanhuu-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBH2IHmzZcXKefSaKRJRICG6UQdCWnQJac',
    appId: '1:785051614310:ios:2beacaf2d63a3fa4f481a7',
    messagingSenderId: '785051614310',
    projectId: 'sanhuu-app',
    storageBucket: 'sanhuu-app.firebasestorage.app',
    iosBundleId: 'com.example.sanhuuApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBH2IHmzZcXKefSaKRJRICG6UQdCWnQJac',
    appId: '1:785051614310:ios:2beacaf2d63a3fa4f481a7',
    messagingSenderId: '785051614310',
    projectId: 'sanhuu-app',
    storageBucket: 'sanhuu-app.firebasestorage.app',
    iosBundleId: 'com.example.sanhuuApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeeC-BvOGV3d8GEJPou6fLWRo_PbgHP0c',
    appId: '1:785051614310:web:90dc1b752b657c3af481a7',
    messagingSenderId: '785051614310',
    projectId: 'sanhuu-app',
    authDomain: 'sanhuu-app.firebaseapp.com',
    storageBucket: 'sanhuu-app.firebasestorage.app',
    measurementId: 'G-9GK2YD6ZCB',
  );
}
